<?php
// $Id: citebank_fedora_commons.module,v 1.0.0.0 2011/03/02 4:44:44 dlheskett $

/** citebank_fedora_commons.module
 *
 * Copyright (c) 2011 Missouri Botanical Garden 
 *
 * @author: David L. Heskett (contractor: Adaptive Solutions Group)
 * @date Created: 03/02/2011
 *
 */

//define('DOS_MODE', true);
define('DOS_MODE', false);

define('IMPORT_DIR_PATH_FILES', '/sites/default/files/');


$includePath = dirname(__FILE__) . '/';

require_once($includePath . 'FedoraController.php');

/**
 * citebank_fedora_commons_view - 
 */
function citebank_fedora_commons_view(&$node, $teaser = FALSE, $page = FALSE)
{
	//echo 'here i am';
}

/**
 * citebank_fedora_commons_cron - 
 */
function citebank_fedora_commons_cron(&$node = null, $teaser = FALSE, $page = FALSE)
{
	// we need an off switch if processed that file.
	fedora_watchmen('Citebank Fedora cron');
	processCiteBankFedoraCommons();
}

/**
 * citebank_fedora_commons_node_info - 
 */
function citebank_fedora_commons_node_info()
{
	return array(
		'citebank_fedora_commons' => array(
			'name'         => t('citebank_fedora_commons'),
			'module'       => 'citebank_fedora_commons',
			'description'  => t('Citebank Fedora Commons: Pass citations and uploaded files from Biblio into Fedora via FOXML.'),
			'has_title'    => TRUE,
			'title_label'  => t('CiteBank Fedora'),
			'has_body'     => FALSE
//			'' => '',
		)
	);
}

// ************************************************************
//  process import methods
// ************************************************************

/**
 *  processCiteBankFedoraCommons - 
 */
function processCiteBankFedoraCommons()
{
	$fedoraController = new FedoraController();
	
	// let us limit the number of records we handle per run
	$fedoraController->throttleFlag = true;
	$fedoraController->throttle = 100;
	
	fedora_watchmen('collecting citations, adding new ones, ready for fedora');
	// add nodes to list and line them up for transfer
	$countItems = $fedoraController->processCitationsCollection();
	
	$throttleMsg = ($fedoraController->throttleFlag ? ' (throttled ' . $fedoraController->throttle . ')' : '');
	fedora_watchmen('process and send ' . $countItems . ' citations to fedora' . $throttleMsg . '');
	// take biblio citations that are ready and send them to our fedora repository
	$fedoraController->processCitations();
}


//watchdog($type, $message, $variables = array(), $severity = WATCHDOG_NOTICE, $link = NULL);
/**
 * watchmen - handy drupal watch logger, give it a msg and go
 */
function fedora_watchmen($msg, $watchFlag = true, $type = 'FedoraImp', $addDate = true)
{
	if ($watchFlag) {
		if ($addDate) {
			$msg .= ' ' . date('YmdHis');
		}
		
		watchdog($type, $msg);  // drupal system call
	}
}

// ************************************************************
// ************************************************************
