<?php
global $user;
$showFlag = true;
// security check
if (!($user->uid == 1 || $user->uid == 3 || $user->uid == 60 || $user->uid == 52)) {
 //print_r('No stats available');
 //return;
$showFlag = false;
}

$includePath = dirname(__FILE__) . '/';
$modulesPath = $includePath . '../sites/all/modules/citebank_importer/';
require_once($modulesPath . 'DBInterfaceController.php');

/**
 * class DBInterfaceController  - database interface to simplify database setup and calling
 *
 */
class DBInterfaceController_stats extends DBInterfaceController
{
}

$dbi = new DBInterfaceController_stats();


statsEchoLine();
statsEchoDate();
statsEchoLine();

if ($showFlag) {

// total citations
$msg = '	Total citations: ';
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) WHERE n.type = 'biblio'";
$totalCitations = getStat($dbi, $msg, $sql);
echo '<br>';

//	* Citations with PDFs from BHL: 
//$msg = '	* Citations with PDFs from BHL: ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%.pdf' AND c.link LIKE '%biodiversity%'";
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%.pdf'";
//$sql = "SELECT COUNT(DISTINCT c.nid) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND b.biblio_label LIKE '%biodiversity%' AND (b.biblio_type = 100 OR b.biblio_type = 102 OR b.biblio_type = 131) AND c.link LIKE '%.pdf'";
//getStat($dbi, $msg, $sql);

//	* Citations without PDFs attached: 
//$msg = '	* Citations without PDFs attached: ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link NOT LIKE '%.pdf'";
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND (c.link NOT LIKE '%.pdf' AND c.link NOT LIKE '%archive.org%' AND c.link NOT LIKE '%citebank.org%')";
//getStat($dbi, $msg, $sql);

//	* Citations from BHL: 
//SELECT COUNT(*) FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) WHERE TYPE = 'biblio' AND b.biblio_url LIKE '%biodiversity%'
$msg = '	Citations from BHL Portal (OAI-PMH ingest): ';
$sql = "SELECT COUNT(*) AS total FROM biblio WHERE biblio_label LIKE '%biodiversity%'";
getStat($dbi, $msg, $sql);

//	* Citations from BHL xxx: 
//$msg = '	* BHL Digitized Titles (books and journals): ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%biodiversitylibrary.org/bibliography%' AND biblio_remote_db_provider > ''";
//getStat($dbi, $msg, $sql);

$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BHL Titles - Books: ';
$sql = "SELECT COUNT(*) AS total FROM biblio WHERE biblio_label LIKE '%biodiversity%' AND biblio_type = 100";getStat($dbi, $msg, $sql);

$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; BHL Titles - Journals: ';
$sql = "SELECT COUNT(*) AS total FROM biblio WHERE biblio_label LIKE '%biodiversity%' AND biblio_type = 131";
getStat($dbi, $msg, $sql);

$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BHL Articles (PDFs generated by users): ';
$sql = "SELECT COUNT(*) AS total FROM biblio WHERE biblio_label LIKE '%biodiversity%' AND biblio_type = 102";
getStat($dbi, $msg, $sql);

echo '<br>';
echo '<br>';
echo 'Citations from other sources (OAI-PMH ingest): count';
echo '<br>';

//$msg = '	* BHL Digitized Titles (Book and Journal records): ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%biodiversity%'";
//getStat($dbi, $msg, $sql);

$msg = '	Citations from SCIELO: ';
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%scielo%'";
getStat($dbi, $msg, $sql);
echo '<br>';

//	* Citations from Scielo: 
// needs a refined search
//$msg = '	* Brazilian Journal of Medical and Biological Research: ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%scielo%'";
//getStat($dbi, $msg, $sql);

// needs a refined search
//$msg = '	* Revista de Saude Publica: ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%scielo%'";
//getStat($dbi, $msg, $sql);

////	* Citations from various sources: 
//$msg = '	* Citations from various sources: ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%handle.net%'";
//getStat($dbi, $msg, $sql);

//	* Citations from Pensoft: 
$msg = '	Citations from Pensoft: ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND b.biblio_label LIKE '%pensof%'";
$sql = "SELECT COUNT(*) AS total FROM biblio WHERE biblio_label LIKE '%Pensoft%'";
getStat($dbi, $msg, $sql);

//	* Citations from Zookeys: 
$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Zookeys: ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND (c.link LIKE '%zookey%' OR b.biblio_url LIKE '%zookey%') AND b.biblio_label LIKE '%pensof%'";
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) WHERE n.type = 'biblio' AND b.biblio_url LIKE '%zookeys%' AND b.biblio_label LIKE '%pensof%'";
getStat($dbi, $msg, $sql);

//	* Citations from Phytokeys: 
$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Phytokeys: ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND (c.link LIKE '%phytokeys%' OR b.biblio_url LIKE '%phytokeys%') AND b.biblio_label LIKE '%pensof%'";
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) WHERE n.type = 'biblio' AND b.biblio_url LIKE '%phytokeys%' AND b.biblio_label LIKE '%pensof%'";
getStat($dbi, $msg, $sql);


// add other sets
//	* Pensoft set: 
$setName = 'Journal Of Hymenoptera Research';
$setKey  = 'journal_of_hymenoptera_research';
$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$setName.': ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND (c.link LIKE '%phytokeys%' OR b.biblio_url LIKE '%phytokeys%') AND b.biblio_label LIKE '%pensof%'";
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) WHERE n.type = 'biblio' AND b.biblio_url LIKE '%".$setKey."%' AND b.biblio_label LIKE '%pensof%'";
getStat($dbi, $msg, $sql);


//	* Pensoft set: 
$setName = 'Int. Jour. Of Myriapodology';
$setKey  = 'international_journal_of_myriapodology';
$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$setName.': ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND (c.link LIKE '%phytokeys%' OR b.biblio_url LIKE '%phytokeys%') AND b.biblio_label LIKE '%pensof%'";
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) WHERE n.type = 'biblio' AND b.biblio_url LIKE '%".$setKey."%' AND b.biblio_label LIKE '%pensof%'";
getStat($dbi, $msg, $sql);

//	* Pensoft set: 
$setName = 'Journal of Comparative Cytogenetics';
$setKey  = 'comparative_cytogenetics';
$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$setName.': ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND (c.link LIKE '%phytokeys%' OR b.biblio_url LIKE '%phytokeys%') AND b.biblio_label LIKE '%pensof%'";
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) WHERE n.type = 'biblio' AND b.biblio_url LIKE '%".$setKey."%' AND b.biblio_label LIKE '%pensof%'";
getStat($dbi, $msg, $sql);

//	* Pensoft set: 
$setName = 'Subterranean Biology';
$setKey  = 'subterranean_biology';
$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$setName.': ';
//$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND (c.link LIKE '%phytokeys%' OR b.biblio_url LIKE '%phytokeys%') AND b.biblio_label LIKE '%pensof%'";
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) WHERE n.type = 'biblio' AND b.biblio_url LIKE '%".$setKey."%' AND b.biblio_label LIKE '%pensof%'";
getStat($dbi, $msg, $sql);

echo '<br>';

//	* Citations from SIL: 
$msg = '	Citations from SIL: ';
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%handle.net%'";
getStat($dbi, $msg, $sql);

//	* Citations from SIL: 
$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Contrributions to Zoology: ';
// FIXME: needs refined search
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%handle.net%'";
getStat($dbi, $msg, $sql);

//	* Citations from SIL: 
$msg = '	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Atoll Research Bulletin: ';
// FIXME: needs refined search
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND c.link LIKE '%handle.net%'";
getStat($dbi, $msg, $sql);


echo '<br>';

//	* Citations from AMNH: 
//$msg = '	* Citations from AMNH (American Museum of Natural History): ';
$msg = '	Citations from AMNH: ';
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND b.biblio_label LIKE '%AMNH%'";
getStat($dbi, $msg, $sql);

echo '<br>';
echo '<br>';
echo 'Citations from other sources (manual ingest):';
echo '<br>';

//	* Citations from 
//$msg = '	* Citations from Biblioteca Digital del Real Jardín Botánico de Madrid - CSIC: ';
$msg = '	Citations from RJB Madrid: ';
$searchKey = 'RJB Madrid';
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND b.biblio_remote_db_provider LIKE '%CSIC%'";
getStat($dbi, $msg, $sql);



//	* Citations from Journal of the American Mosquito Control Association: 
//$msg = '	* Citations from Journal of the American Mosquito Control Association: ';
$msg = '	Citations from JAMCA: ';
$searchKey = 'Journal of the American Mosquito Control Association';
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND b.biblio_label LIKE '%".$searchKey."%'";
getStat($dbi, $msg, $sql);

//	* Citations from 
$msg = '	Citations from JEANH: ';
$searchKey = 'JEANH';
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND b.biblio_label LIKE '%".$searchKey."%'";
getStat($dbi, $msg, $sql);

//	* Citations from 
$msg = '	Citations from Charles Drechsler Articles: ';
$searchKey = 'Drechsler';
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) JOIN citebank_unique_identifier as c ON (b.nid = c.nid) WHERE n.type = 'biblio' AND b.biblio_label LIKE '%".$searchKey."%'";
getStat($dbi, $msg, $sql);





statsEchoLine();

//	* Registerered CiteBank users: 
$msg = '	Registerered CiteBank users: ';
$sql = "SELECT COUNT(*) AS total FROM users";
$numTotalUsers = getStat($dbi, $msg, $sql);

//	* Registerered CiteBank users: 
$msg = '	active: ';
$sql = "SELECT COUNT(*) AS total FROM users WHERE STATUS = 1";
$numUsersActive = getStat($dbi, $msg, $sql);

//	* Registerered CiteBank users: 
$msg = '	active (that have accessed site): ';
$sql = "SELECT COUNT(*) AS total FROM users WHERE STATUS = 1 AND access > 0 AND login > 0";
$numUsersActive = getStat($dbi, $msg, $sql);

$msg = '	blocked: ';
$sql = "SELECT COUNT(*) AS total FROM users WHERE STATUS = 0";
$numUsersBlocked = getStat($dbi, $msg, $sql);

statsEchoLine();

// total citations sent to IA
$msg = '	Total citations sent to IA (Citations in CB (internally hosted content files)): ';
$sql = "SELECT COUNT(DISTINCT nid) AS total FROM citebank_internet_archive_records WHERE archive_status > 0";
$totalIACitations = getStat($dbi, $msg, $sql);

$percentageToIA = round(($totalIACitations / $totalCitations) * 100);
	echo '<br>';
	$msg = '	Percentage Citations sent to IA: ';
	echo $msg . $percentageToIA . '%';

// total citations in queue for IA
$msg = '	Total citations in queue to IA: ';
$sql = "SELECT COUNT(DISTINCT nid) AS total FROM citebank_internet_archive_records WHERE archive_status = 0";
getStat($dbi, $msg, $sql);

// total citations on hold for IA
$msg = '	Total citations on hold for IA: ';
$sql = "SELECT COUNT(DISTINCT nid) AS total FROM citebank_internet_archive_records WHERE archive_status < -1";
getStat($dbi, $msg, $sql);

// total citations on ignored for IA
$msg = '	Total citations ignored for IA: ';
$sql = "SELECT COUNT(DISTINCT nid) AS total FROM citebank_internet_archive_records WHERE archive_status = -1";
getStat($dbi, $msg, $sql);

$totalCitationsExternallyHosted = $totalCitations - $totalIACitations;
echo '<br>';
$msg = '	Citations in CB (externally hosted content files): ';
echo $msg . $totalCitationsExternallyHosted;

// ****************************************
// ****************************************
// ****************************************

} else { // just public stats
// total citations
$msg = '	Total citations: ';
$sql = "SELECT COUNT(*) AS total FROM node AS n JOIN biblio AS b ON (n.nid = b.nid) WHERE n.type = 'biblio'";
getStat($dbi, $msg, $sql);



}

statsEchoLine();


/*
 *
 */
function getStat($dbi, $msg, $sql)
{
	$rows = $dbi->fetch($sql);
	$count = 0;
	if (count($rows) > 0) {
		$count = $rows[0]['total'];
	}
	
	echo '<br>';
	echo $msg . $count;
	
	return $count;
}

/*
 *
 */
function statsEchoLine()
{
	echo '<br>';
	echo '<hr>';
//	echo '-----------------------------------------------------------------------';
	echo '<br>';
	
}

/*
 *
 */
function statsEchoDate()
{
	//citestats - CiteBank stats updated Thu Nov 17 01:01:01 CST 2011	
	echo '<br>';
	echo 'citestats - CiteBank stats updated ' .  date('D M d Y H:i:s T') . ' 	';
	echo '<br>';

	
}

?>
