//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
// 
#pragma warning disable 1591

namespace MOBOT.BHL.Web.BHLImportWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BHLImportWSSoap", Namespace="http://www.mobot.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomObjectBase))]
    public partial class BHLImportWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IAItemSelectPendingApprovalOperationCompleted;
        
        private System.Threading.SendOrPostCallback BotanicusHarvestLogSelectRecentOperationCompleted;
        
        private System.Threading.SendOrPostCallback IAItemErrorSelectRecentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportErrorSelectRecentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportLogSelectRecentOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatsSelectReadyForProductionBySourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatsCountIAItemPendingApprovalOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatsSelectIAItemGroupByStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatsSelectIAItemPendingApprovalGroupByAgeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BHLImportWS() {
            this.Url = global::MOBOT.BHL.Web.Properties.Settings.Default.MOBOT_BHL_Web_BHLImportWebService_BHLImportWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IAItemSelectPendingApprovalCompletedEventHandler IAItemSelectPendingApprovalCompleted;
        
        /// <remarks/>
        public event BotanicusHarvestLogSelectRecentCompletedEventHandler BotanicusHarvestLogSelectRecentCompleted;
        
        /// <remarks/>
        public event IAItemErrorSelectRecentCompletedEventHandler IAItemErrorSelectRecentCompleted;
        
        /// <remarks/>
        public event ImportErrorSelectRecentCompletedEventHandler ImportErrorSelectRecentCompleted;
        
        /// <remarks/>
        public event ImportLogSelectRecentCompletedEventHandler ImportLogSelectRecentCompleted;
        
        /// <remarks/>
        public event StatsSelectReadyForProductionBySourceCompletedEventHandler StatsSelectReadyForProductionBySourceCompleted;
        
        /// <remarks/>
        public event StatsCountIAItemPendingApprovalCompletedEventHandler StatsCountIAItemPendingApprovalCompleted;
        
        /// <remarks/>
        public event StatsSelectIAItemGroupByStatusCompletedEventHandler StatsSelectIAItemGroupByStatusCompleted;
        
        /// <remarks/>
        public event StatsSelectIAItemPendingApprovalGroupByAgeCompletedEventHandler StatsSelectIAItemPendingApprovalGroupByAgeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mobot.org/IAItemSelectPendingApproval", RequestNamespace="http://www.mobot.org/", ResponseNamespace="http://www.mobot.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IAItem[] IAItemSelectPendingApproval(int ageInDays) {
            object[] results = this.Invoke("IAItemSelectPendingApproval", new object[] {
                        ageInDays});
            return ((IAItem[])(results[0]));
        }
        
        /// <remarks/>
        public void IAItemSelectPendingApprovalAsync(int ageInDays) {
            this.IAItemSelectPendingApprovalAsync(ageInDays, null);
        }
        
        /// <remarks/>
        public void IAItemSelectPendingApprovalAsync(int ageInDays, object userState) {
            if ((this.IAItemSelectPendingApprovalOperationCompleted == null)) {
                this.IAItemSelectPendingApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIAItemSelectPendingApprovalOperationCompleted);
            }
            this.InvokeAsync("IAItemSelectPendingApproval", new object[] {
                        ageInDays}, this.IAItemSelectPendingApprovalOperationCompleted, userState);
        }
        
        private void OnIAItemSelectPendingApprovalOperationCompleted(object arg) {
            if ((this.IAItemSelectPendingApprovalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IAItemSelectPendingApprovalCompleted(this, new IAItemSelectPendingApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mobot.org/BotanicusHarvestLogSelectRecent", RequestNamespace="http://www.mobot.org/", ResponseNamespace="http://www.mobot.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BotanicusHarvestLog[] BotanicusHarvestLogSelectRecent(int numLogs) {
            object[] results = this.Invoke("BotanicusHarvestLogSelectRecent", new object[] {
                        numLogs});
            return ((BotanicusHarvestLog[])(results[0]));
        }
        
        /// <remarks/>
        public void BotanicusHarvestLogSelectRecentAsync(int numLogs) {
            this.BotanicusHarvestLogSelectRecentAsync(numLogs, null);
        }
        
        /// <remarks/>
        public void BotanicusHarvestLogSelectRecentAsync(int numLogs, object userState) {
            if ((this.BotanicusHarvestLogSelectRecentOperationCompleted == null)) {
                this.BotanicusHarvestLogSelectRecentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBotanicusHarvestLogSelectRecentOperationCompleted);
            }
            this.InvokeAsync("BotanicusHarvestLogSelectRecent", new object[] {
                        numLogs}, this.BotanicusHarvestLogSelectRecentOperationCompleted, userState);
        }
        
        private void OnBotanicusHarvestLogSelectRecentOperationCompleted(object arg) {
            if ((this.BotanicusHarvestLogSelectRecentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BotanicusHarvestLogSelectRecentCompleted(this, new BotanicusHarvestLogSelectRecentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mobot.org/IAItemErrorSelectRecent", RequestNamespace="http://www.mobot.org/", ResponseNamespace="http://www.mobot.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IAItemError[] IAItemErrorSelectRecent(int numErrors) {
            object[] results = this.Invoke("IAItemErrorSelectRecent", new object[] {
                        numErrors});
            return ((IAItemError[])(results[0]));
        }
        
        /// <remarks/>
        public void IAItemErrorSelectRecentAsync(int numErrors) {
            this.IAItemErrorSelectRecentAsync(numErrors, null);
        }
        
        /// <remarks/>
        public void IAItemErrorSelectRecentAsync(int numErrors, object userState) {
            if ((this.IAItemErrorSelectRecentOperationCompleted == null)) {
                this.IAItemErrorSelectRecentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIAItemErrorSelectRecentOperationCompleted);
            }
            this.InvokeAsync("IAItemErrorSelectRecent", new object[] {
                        numErrors}, this.IAItemErrorSelectRecentOperationCompleted, userState);
        }
        
        private void OnIAItemErrorSelectRecentOperationCompleted(object arg) {
            if ((this.IAItemErrorSelectRecentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IAItemErrorSelectRecentCompleted(this, new IAItemErrorSelectRecentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mobot.org/ImportErrorSelectRecent", RequestNamespace="http://www.mobot.org/", ResponseNamespace="http://www.mobot.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ImportError[] ImportErrorSelectRecent(int numErrors) {
            object[] results = this.Invoke("ImportErrorSelectRecent", new object[] {
                        numErrors});
            return ((ImportError[])(results[0]));
        }
        
        /// <remarks/>
        public void ImportErrorSelectRecentAsync(int numErrors) {
            this.ImportErrorSelectRecentAsync(numErrors, null);
        }
        
        /// <remarks/>
        public void ImportErrorSelectRecentAsync(int numErrors, object userState) {
            if ((this.ImportErrorSelectRecentOperationCompleted == null)) {
                this.ImportErrorSelectRecentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportErrorSelectRecentOperationCompleted);
            }
            this.InvokeAsync("ImportErrorSelectRecent", new object[] {
                        numErrors}, this.ImportErrorSelectRecentOperationCompleted, userState);
        }
        
        private void OnImportErrorSelectRecentOperationCompleted(object arg) {
            if ((this.ImportErrorSelectRecentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportErrorSelectRecentCompleted(this, new ImportErrorSelectRecentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mobot.org/ImportLogSelectRecent", RequestNamespace="http://www.mobot.org/", ResponseNamespace="http://www.mobot.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ImportLog[] ImportLogSelectRecent(int numLogs) {
            object[] results = this.Invoke("ImportLogSelectRecent", new object[] {
                        numLogs});
            return ((ImportLog[])(results[0]));
        }
        
        /// <remarks/>
        public void ImportLogSelectRecentAsync(int numLogs) {
            this.ImportLogSelectRecentAsync(numLogs, null);
        }
        
        /// <remarks/>
        public void ImportLogSelectRecentAsync(int numLogs, object userState) {
            if ((this.ImportLogSelectRecentOperationCompleted == null)) {
                this.ImportLogSelectRecentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportLogSelectRecentOperationCompleted);
            }
            this.InvokeAsync("ImportLogSelectRecent", new object[] {
                        numLogs}, this.ImportLogSelectRecentOperationCompleted, userState);
        }
        
        private void OnImportLogSelectRecentOperationCompleted(object arg) {
            if ((this.ImportLogSelectRecentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportLogSelectRecentCompleted(this, new ImportLogSelectRecentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mobot.org/StatsSelectReadyForProductionBySource", RequestNamespace="http://www.mobot.org/", ResponseNamespace="http://www.mobot.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Stats[] StatsSelectReadyForProductionBySource(int importSourceID) {
            object[] results = this.Invoke("StatsSelectReadyForProductionBySource", new object[] {
                        importSourceID});
            return ((Stats[])(results[0]));
        }
        
        /// <remarks/>
        public void StatsSelectReadyForProductionBySourceAsync(int importSourceID) {
            this.StatsSelectReadyForProductionBySourceAsync(importSourceID, null);
        }
        
        /// <remarks/>
        public void StatsSelectReadyForProductionBySourceAsync(int importSourceID, object userState) {
            if ((this.StatsSelectReadyForProductionBySourceOperationCompleted == null)) {
                this.StatsSelectReadyForProductionBySourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatsSelectReadyForProductionBySourceOperationCompleted);
            }
            this.InvokeAsync("StatsSelectReadyForProductionBySource", new object[] {
                        importSourceID}, this.StatsSelectReadyForProductionBySourceOperationCompleted, userState);
        }
        
        private void OnStatsSelectReadyForProductionBySourceOperationCompleted(object arg) {
            if ((this.StatsSelectReadyForProductionBySourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatsSelectReadyForProductionBySourceCompleted(this, new StatsSelectReadyForProductionBySourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mobot.org/StatsCountIAItemPendingApproval", RequestNamespace="http://www.mobot.org/", ResponseNamespace="http://www.mobot.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Stats StatsCountIAItemPendingApproval(int ageInDays) {
            object[] results = this.Invoke("StatsCountIAItemPendingApproval", new object[] {
                        ageInDays});
            return ((Stats)(results[0]));
        }
        
        /// <remarks/>
        public void StatsCountIAItemPendingApprovalAsync(int ageInDays) {
            this.StatsCountIAItemPendingApprovalAsync(ageInDays, null);
        }
        
        /// <remarks/>
        public void StatsCountIAItemPendingApprovalAsync(int ageInDays, object userState) {
            if ((this.StatsCountIAItemPendingApprovalOperationCompleted == null)) {
                this.StatsCountIAItemPendingApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatsCountIAItemPendingApprovalOperationCompleted);
            }
            this.InvokeAsync("StatsCountIAItemPendingApproval", new object[] {
                        ageInDays}, this.StatsCountIAItemPendingApprovalOperationCompleted, userState);
        }
        
        private void OnStatsCountIAItemPendingApprovalOperationCompleted(object arg) {
            if ((this.StatsCountIAItemPendingApprovalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatsCountIAItemPendingApprovalCompleted(this, new StatsCountIAItemPendingApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mobot.org/StatsSelectIAItemGroupByStatus", RequestNamespace="http://www.mobot.org/", ResponseNamespace="http://www.mobot.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Stats[] StatsSelectIAItemGroupByStatus() {
            object[] results = this.Invoke("StatsSelectIAItemGroupByStatus", new object[0]);
            return ((Stats[])(results[0]));
        }
        
        /// <remarks/>
        public void StatsSelectIAItemGroupByStatusAsync() {
            this.StatsSelectIAItemGroupByStatusAsync(null);
        }
        
        /// <remarks/>
        public void StatsSelectIAItemGroupByStatusAsync(object userState) {
            if ((this.StatsSelectIAItemGroupByStatusOperationCompleted == null)) {
                this.StatsSelectIAItemGroupByStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatsSelectIAItemGroupByStatusOperationCompleted);
            }
            this.InvokeAsync("StatsSelectIAItemGroupByStatus", new object[0], this.StatsSelectIAItemGroupByStatusOperationCompleted, userState);
        }
        
        private void OnStatsSelectIAItemGroupByStatusOperationCompleted(object arg) {
            if ((this.StatsSelectIAItemGroupByStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatsSelectIAItemGroupByStatusCompleted(this, new StatsSelectIAItemGroupByStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mobot.org/StatsSelectIAItemPendingApprovalGroupByAge", RequestNamespace="http://www.mobot.org/", ResponseNamespace="http://www.mobot.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Stats[] StatsSelectIAItemPendingApprovalGroupByAge(int ageInDays) {
            object[] results = this.Invoke("StatsSelectIAItemPendingApprovalGroupByAge", new object[] {
                        ageInDays});
            return ((Stats[])(results[0]));
        }
        
        /// <remarks/>
        public void StatsSelectIAItemPendingApprovalGroupByAgeAsync(int ageInDays) {
            this.StatsSelectIAItemPendingApprovalGroupByAgeAsync(ageInDays, null);
        }
        
        /// <remarks/>
        public void StatsSelectIAItemPendingApprovalGroupByAgeAsync(int ageInDays, object userState) {
            if ((this.StatsSelectIAItemPendingApprovalGroupByAgeOperationCompleted == null)) {
                this.StatsSelectIAItemPendingApprovalGroupByAgeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatsSelectIAItemPendingApprovalGroupByAgeOperationCompleted);
            }
            this.InvokeAsync("StatsSelectIAItemPendingApprovalGroupByAge", new object[] {
                        ageInDays}, this.StatsSelectIAItemPendingApprovalGroupByAgeOperationCompleted, userState);
        }
        
        private void OnStatsSelectIAItemPendingApprovalGroupByAgeOperationCompleted(object arg) {
            if ((this.StatsSelectIAItemPendingApprovalGroupByAgeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatsSelectIAItemPendingApprovalGroupByAgeCompleted(this, new StatsSelectIAItemPendingApprovalGroupByAgeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class IAItem : @__IAItem {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__IAItem : CustomObjectBase {
        
        private int itemIDField;
        
        private int itemStatusIDField;
        
        private string iAIdentifierPrefixField;
        
        private string iAIdentifierField;
        
        private string sponsorField;
        
        private string sponsorNameField;
        
        private string sponsorDateField;
        
        private string scanningCenterField;
        
        private string callNumberField;
        
        private System.Nullable<int> imageCountField;
        
        private string identifierAccessUrlField;
        
        private string volumeField;
        
        private string noteField;
        
        private string scanOperatorField;
        
        private string scanDateField;
        
        private string externalStatusField;
        
        private string titleIDField;
        
        private string yearField;
        
        private string identifierBibField;
        
        private string mARCBibIDField;
        
        private string shortTitleField;
        
        private string barCodeField;
        
        private System.Nullable<System.DateTime> iADateStampField;
        
        private System.Nullable<System.DateTime> iAAddedDateField;
        
        private System.Nullable<System.DateTime> lastOAIDataHarvestDateField;
        
        private System.Nullable<System.DateTime> lastXMLDataHarvestDateField;
        
        private System.Nullable<System.DateTime> lastProductionDateField;
        
        private System.DateTime createdDateField;
        
        private System.DateTime lastModifiedDateField;
        
        /// <remarks/>
        public int ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public int ItemStatusID {
            get {
                return this.itemStatusIDField;
            }
            set {
                this.itemStatusIDField = value;
            }
        }
        
        /// <remarks/>
        public string IAIdentifierPrefix {
            get {
                return this.iAIdentifierPrefixField;
            }
            set {
                this.iAIdentifierPrefixField = value;
            }
        }
        
        /// <remarks/>
        public string IAIdentifier {
            get {
                return this.iAIdentifierField;
            }
            set {
                this.iAIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string Sponsor {
            get {
                return this.sponsorField;
            }
            set {
                this.sponsorField = value;
            }
        }
        
        /// <remarks/>
        public string SponsorName {
            get {
                return this.sponsorNameField;
            }
            set {
                this.sponsorNameField = value;
            }
        }
        
        /// <remarks/>
        public string SponsorDate {
            get {
                return this.sponsorDateField;
            }
            set {
                this.sponsorDateField = value;
            }
        }
        
        /// <remarks/>
        public string ScanningCenter {
            get {
                return this.scanningCenterField;
            }
            set {
                this.scanningCenterField = value;
            }
        }
        
        /// <remarks/>
        public string CallNumber {
            get {
                return this.callNumberField;
            }
            set {
                this.callNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ImageCount {
            get {
                return this.imageCountField;
            }
            set {
                this.imageCountField = value;
            }
        }
        
        /// <remarks/>
        public string IdentifierAccessUrl {
            get {
                return this.identifierAccessUrlField;
            }
            set {
                this.identifierAccessUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public string ScanOperator {
            get {
                return this.scanOperatorField;
            }
            set {
                this.scanOperatorField = value;
            }
        }
        
        /// <remarks/>
        public string ScanDate {
            get {
                return this.scanDateField;
            }
            set {
                this.scanDateField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalStatus {
            get {
                return this.externalStatusField;
            }
            set {
                this.externalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string TitleID {
            get {
                return this.titleIDField;
            }
            set {
                this.titleIDField = value;
            }
        }
        
        /// <remarks/>
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string IdentifierBib {
            get {
                return this.identifierBibField;
            }
            set {
                this.identifierBibField = value;
            }
        }
        
        /// <remarks/>
        public string MARCBibID {
            get {
                return this.mARCBibIDField;
            }
            set {
                this.mARCBibIDField = value;
            }
        }
        
        /// <remarks/>
        public string ShortTitle {
            get {
                return this.shortTitleField;
            }
            set {
                this.shortTitleField = value;
            }
        }
        
        /// <remarks/>
        public string BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> IADateStamp {
            get {
                return this.iADateStampField;
            }
            set {
                this.iADateStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> IAAddedDate {
            get {
                return this.iAAddedDateField;
            }
            set {
                this.iAAddedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastOAIDataHarvestDate {
            get {
                return this.lastOAIDataHarvestDateField;
            }
            set {
                this.lastOAIDataHarvestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastXMLDataHarvestDate {
            get {
                return this.lastXMLDataHarvestDateField;
            }
            set {
                this.lastXMLDataHarvestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastProductionDate {
            get {
                return this.lastProductionDateField;
            }
            set {
                this.lastProductionDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__ImportLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__ImportError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__IAItemError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItemError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__BotanicusHarvestLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BotanicusHarvestLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__IAItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class CustomObjectBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class Stats {
        
        private int numberOfItemsField;
        
        private int ageInDaysField;
        
        private int itemStatusIDField;
        
        private string statusField;
        
        private string descriptionField;
        
        private string sourceField;
        
        private string typeField;
        
        /// <remarks/>
        public int NumberOfItems {
            get {
                return this.numberOfItemsField;
            }
            set {
                this.numberOfItemsField = value;
            }
        }
        
        /// <remarks/>
        public int AgeInDays {
            get {
                return this.ageInDaysField;
            }
            set {
                this.ageInDaysField = value;
            }
        }
        
        /// <remarks/>
        public int ItemStatusID {
            get {
                return this.itemStatusIDField;
            }
            set {
                this.itemStatusIDField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportLog))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__ImportLog : CustomObjectBase {
        
        private int importLogIDField;
        
        private System.DateTime importDateField;
        
        private System.Nullable<int> importSourceIDField;
        
        private string barCodeField;
        
        private string importResultField;
        
        private int titleInsertField;
        
        private int titleUpdateField;
        
        private int creatorInsertField;
        
        private int creatorUpdateField;
        
        private int titleCreatorInsertField;
        
        private int titleCreatorUpdateField;
        
        private int titleTagInsertField;
        
        private int titleTagUpdateField;
        
        private System.Nullable<int> titleTitleIdentifierInsertField;
        
        private System.Nullable<int> titleTitleIdentifierUpdateField;
        
        private System.Nullable<int> titleAssociationInsertField;
        
        private System.Nullable<int> titleAssociationTitleIdentifierInsertField;
        
        private int itemInsertField;
        
        private int itemUpdateField;
        
        private System.Nullable<int> titleItemInsertField;
        
        private int pageInsertField;
        
        private int pageUpdateField;
        
        private int indicatedPageInsertField;
        
        private int indicatedPageUpdateField;
        
        private int pagePageTypeInsertField;
        
        private int pagePageTypeUpdateField;
        
        private int pageNameInsertField;
        
        private int pageNameUpdateField;
        
        /// <remarks/>
        public int ImportLogID {
            get {
                return this.importLogIDField;
            }
            set {
                this.importLogIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ImportDate {
            get {
                return this.importDateField;
            }
            set {
                this.importDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ImportSourceID {
            get {
                return this.importSourceIDField;
            }
            set {
                this.importSourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ImportResult {
            get {
                return this.importResultField;
            }
            set {
                this.importResultField = value;
            }
        }
        
        /// <remarks/>
        public int TitleInsert {
            get {
                return this.titleInsertField;
            }
            set {
                this.titleInsertField = value;
            }
        }
        
        /// <remarks/>
        public int TitleUpdate {
            get {
                return this.titleUpdateField;
            }
            set {
                this.titleUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int CreatorInsert {
            get {
                return this.creatorInsertField;
            }
            set {
                this.creatorInsertField = value;
            }
        }
        
        /// <remarks/>
        public int CreatorUpdate {
            get {
                return this.creatorUpdateField;
            }
            set {
                this.creatorUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int TitleCreatorInsert {
            get {
                return this.titleCreatorInsertField;
            }
            set {
                this.titleCreatorInsertField = value;
            }
        }
        
        /// <remarks/>
        public int TitleCreatorUpdate {
            get {
                return this.titleCreatorUpdateField;
            }
            set {
                this.titleCreatorUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int TitleTagInsert {
            get {
                return this.titleTagInsertField;
            }
            set {
                this.titleTagInsertField = value;
            }
        }
        
        /// <remarks/>
        public int TitleTagUpdate {
            get {
                return this.titleTagUpdateField;
            }
            set {
                this.titleTagUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TitleTitleIdentifierInsert {
            get {
                return this.titleTitleIdentifierInsertField;
            }
            set {
                this.titleTitleIdentifierInsertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TitleTitleIdentifierUpdate {
            get {
                return this.titleTitleIdentifierUpdateField;
            }
            set {
                this.titleTitleIdentifierUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TitleAssociationInsert {
            get {
                return this.titleAssociationInsertField;
            }
            set {
                this.titleAssociationInsertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TitleAssociationTitleIdentifierInsert {
            get {
                return this.titleAssociationTitleIdentifierInsertField;
            }
            set {
                this.titleAssociationTitleIdentifierInsertField = value;
            }
        }
        
        /// <remarks/>
        public int ItemInsert {
            get {
                return this.itemInsertField;
            }
            set {
                this.itemInsertField = value;
            }
        }
        
        /// <remarks/>
        public int ItemUpdate {
            get {
                return this.itemUpdateField;
            }
            set {
                this.itemUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TitleItemInsert {
            get {
                return this.titleItemInsertField;
            }
            set {
                this.titleItemInsertField = value;
            }
        }
        
        /// <remarks/>
        public int PageInsert {
            get {
                return this.pageInsertField;
            }
            set {
                this.pageInsertField = value;
            }
        }
        
        /// <remarks/>
        public int PageUpdate {
            get {
                return this.pageUpdateField;
            }
            set {
                this.pageUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int IndicatedPageInsert {
            get {
                return this.indicatedPageInsertField;
            }
            set {
                this.indicatedPageInsertField = value;
            }
        }
        
        /// <remarks/>
        public int IndicatedPageUpdate {
            get {
                return this.indicatedPageUpdateField;
            }
            set {
                this.indicatedPageUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int PagePageTypeInsert {
            get {
                return this.pagePageTypeInsertField;
            }
            set {
                this.pagePageTypeInsertField = value;
            }
        }
        
        /// <remarks/>
        public int PagePageTypeUpdate {
            get {
                return this.pagePageTypeUpdateField;
            }
            set {
                this.pagePageTypeUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int PageNameInsert {
            get {
                return this.pageNameInsertField;
            }
            set {
                this.pageNameInsertField = value;
            }
        }
        
        /// <remarks/>
        public int PageNameUpdate {
            get {
                return this.pageNameUpdateField;
            }
            set {
                this.pageNameUpdateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class ImportLog : @__ImportLog {
        
        private string importSourceField;
        
        /// <remarks/>
        public string ImportSource {
            get {
                return this.importSourceField;
            }
            set {
                this.importSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportError))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__ImportError : CustomObjectBase {
        
        private int importErrorIDField;
        
        private string keyTypeField;
        
        private string keyValueField;
        
        private System.DateTime errorDateField;
        
        private System.Nullable<int> numberField;
        
        private System.Nullable<int> severityField;
        
        private System.Nullable<int> stateField;
        
        private string procedureField;
        
        private System.Nullable<int> lineField;
        
        private string messageField;
        
        /// <remarks/>
        public int ImportErrorID {
            get {
                return this.importErrorIDField;
            }
            set {
                this.importErrorIDField = value;
            }
        }
        
        /// <remarks/>
        public string KeyType {
            get {
                return this.keyTypeField;
            }
            set {
                this.keyTypeField = value;
            }
        }
        
        /// <remarks/>
        public string KeyValue {
            get {
                return this.keyValueField;
            }
            set {
                this.keyValueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ErrorDate {
            get {
                return this.errorDateField;
            }
            set {
                this.errorDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Procedure {
            get {
                return this.procedureField;
            }
            set {
                this.procedureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class ImportError : @__ImportError {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItemError))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__IAItemError : CustomObjectBase {
        
        private int itemErrorIDField;
        
        private System.Nullable<int> itemIDField;
        
        private System.DateTime errorDateField;
        
        private System.Nullable<int> numberField;
        
        private System.Nullable<int> severityField;
        
        private System.Nullable<int> stateField;
        
        private string procedureField;
        
        private System.Nullable<int> lineField;
        
        private string messageField;
        
        /// <remarks/>
        public int ItemErrorID {
            get {
                return this.itemErrorIDField;
            }
            set {
                this.itemErrorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ErrorDate {
            get {
                return this.errorDateField;
            }
            set {
                this.errorDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Procedure {
            get {
                return this.procedureField;
            }
            set {
                this.procedureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class IAItemError : @__IAItemError {
        
        private string iAIdentifierField;
        
        /// <remarks/>
        public string IAIdentifier {
            get {
                return this.iAIdentifierField;
            }
            set {
                this.iAIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BotanicusHarvestLog))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__BotanicusHarvestLog : CustomObjectBase {
        
        private int botanicusHarvestLogIDField;
        
        private System.DateTime harvestStartDateField;
        
        private System.DateTime harvestEndDateField;
        
        private bool automaticHarvestField;
        
        private bool successfulHarvestField;
        
        private int titleField;
        
        private int titleTagField;
        
        private int titleCreatorField;
        
        private int creatorField;
        
        private int itemField;
        
        private int pageField;
        
        private int indicatedPageField;
        
        private int pagePageTypeField;
        
        private int pageNameField;
        
        /// <remarks/>
        public int BotanicusHarvestLogID {
            get {
                return this.botanicusHarvestLogIDField;
            }
            set {
                this.botanicusHarvestLogIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime HarvestStartDate {
            get {
                return this.harvestStartDateField;
            }
            set {
                this.harvestStartDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime HarvestEndDate {
            get {
                return this.harvestEndDateField;
            }
            set {
                this.harvestEndDateField = value;
            }
        }
        
        /// <remarks/>
        public bool AutomaticHarvest {
            get {
                return this.automaticHarvestField;
            }
            set {
                this.automaticHarvestField = value;
            }
        }
        
        /// <remarks/>
        public bool SuccessfulHarvest {
            get {
                return this.successfulHarvestField;
            }
            set {
                this.successfulHarvestField = value;
            }
        }
        
        /// <remarks/>
        public int Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public int TitleTag {
            get {
                return this.titleTagField;
            }
            set {
                this.titleTagField = value;
            }
        }
        
        /// <remarks/>
        public int TitleCreator {
            get {
                return this.titleCreatorField;
            }
            set {
                this.titleCreatorField = value;
            }
        }
        
        /// <remarks/>
        public int Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        public int Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public int Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        public int IndicatedPage {
            get {
                return this.indicatedPageField;
            }
            set {
                this.indicatedPageField = value;
            }
        }
        
        /// <remarks/>
        public int PagePageType {
            get {
                return this.pagePageTypeField;
            }
            set {
                this.pagePageTypeField = value;
            }
        }
        
        /// <remarks/>
        public int PageName {
            get {
                return this.pageNameField;
            }
            set {
                this.pageNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class BotanicusHarvestLog : @__BotanicusHarvestLog {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void IAItemSelectPendingApprovalCompletedEventHandler(object sender, IAItemSelectPendingApprovalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IAItemSelectPendingApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IAItemSelectPendingApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IAItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IAItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void BotanicusHarvestLogSelectRecentCompletedEventHandler(object sender, BotanicusHarvestLogSelectRecentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BotanicusHarvestLogSelectRecentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BotanicusHarvestLogSelectRecentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BotanicusHarvestLog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BotanicusHarvestLog[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void IAItemErrorSelectRecentCompletedEventHandler(object sender, IAItemErrorSelectRecentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IAItemErrorSelectRecentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IAItemErrorSelectRecentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IAItemError[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IAItemError[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ImportErrorSelectRecentCompletedEventHandler(object sender, ImportErrorSelectRecentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportErrorSelectRecentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportErrorSelectRecentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ImportError[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ImportError[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ImportLogSelectRecentCompletedEventHandler(object sender, ImportLogSelectRecentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportLogSelectRecentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportLogSelectRecentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ImportLog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ImportLog[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void StatsSelectReadyForProductionBySourceCompletedEventHandler(object sender, StatsSelectReadyForProductionBySourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatsSelectReadyForProductionBySourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatsSelectReadyForProductionBySourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Stats[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Stats[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void StatsCountIAItemPendingApprovalCompletedEventHandler(object sender, StatsCountIAItemPendingApprovalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatsCountIAItemPendingApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatsCountIAItemPendingApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Stats Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Stats)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void StatsSelectIAItemGroupByStatusCompletedEventHandler(object sender, StatsSelectIAItemGroupByStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatsSelectIAItemGroupByStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatsSelectIAItemGroupByStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Stats[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Stats[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void StatsSelectIAItemPendingApprovalGroupByAgeCompletedEventHandler(object sender, StatsSelectIAItemPendingApprovalGroupByAgeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatsSelectIAItemPendingApprovalGroupByAgeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatsSelectIAItemPendingApprovalGroupByAgeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Stats[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Stats[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591