<?php
// $Id: citebank_fedora_commons.module,v 1.0.0.0 2011/03/02 4:44:44 dlheskett $

/** citebank_fedora_commons.module
 *
 * Copyright (c) 2011 Missouri Botanical Garden 
 *
 * @author: David L. Heskett (contractor: Adaptive Solutions Group)
 * @date Created: 03/02/2011
 *
 */

$includePath = dirname(__FILE__) . '/';

require_once($includePath . 'FedoraController.php');

/**
 * citebank_fedora_commons_init - 
 */
function citebank_fedora_commons_init()
{
	//menu_rebuild();  // cut this out for production, this is helpful for development only
}

/**
 * citebank_fedora_commons_view - 
 */
function citebank_fedora_commons_view(&$node, $teaser = FALSE, $page = FALSE)
{
	//echo 'here i am';
}

/**
 * citebank_fedora_commons_cron - 
 */
function citebank_fedora_commons_cron(&$node = null, $teaser = FALSE, $page = FALSE)
{
	// handle processing Fedora for Citebank.
	fedora_watchmen('Citebank Fedora cron');
	processCiteBankFedoraCommons();
}

/**
 * citebank_fedora_commons_node_info - 
 */
function citebank_fedora_commons_node_info()
{
	return array(
		'citebank_fedora_commons' => array(
			'name'         => t('citebank_fedora_commons'),
			'module'       => 'citebank_fedora_commons',
			'description'  => t('Citebank Fedora Commons: Pass citations and uploaded files from Biblio into Fedora via FOXML.'),
			'has_title'    => TRUE,
			'title_label'  => t('CiteBank Fedora'),
			'has_body'     => FALSE
//			'' => '',
		)
	);
}

/**
 * citebank_fedora_commons_menu - 
 */
function citebank_fedora_commons_menu()
{
	$items = array();
	
	$items['admin/settings/citebank_fedora_commons/form'] = array(
		'title' => t('Citebank Fedora Commons Configuration Settings'),
    'page callback' => 'citebank_fedora_commons_form',
    'access arguments' => array('access content'),
    'description' => t('Citebank Fedora Commons Configuration'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'user_access',                     // Check that the current user
    'access arguments' => array('Administer Your Module'),  // ... has this permission.    
		'access' => TRUE
	);
	
	return $items;
}

/**
 * citebank_fedora_commons_form - 
 */
function citebank_fedora_commons_form() 
{
	return drupal_get_form('citebank_fedora_commons_configuration_form');
}

/**
 * citebank_fedora_commons_form_submit - 
 */
function citebank_fedora_commons_form_submit($form, &$form_state) 
{
	$now = date('m/d/Y H:i:s');
	drupal_set_message(t('The configuration has been updated. ' . $now));
	
	// make them be integers and not strings, force to either 1 or 0
	$throttleFlag = 0 + (0 + $form_state['values']['throttleFlag'] == 1 ? 1 : 0);
	$loggingFlag  = 0 + (0 + $form_state['values']['loggingFlag']  == 1 ? 1 : 0);
	$processFlag  = 0 + (0 + $form_state['values']['processFlag']  == 1 ? 1 : 0);

	$fedoraUser  = $form_state['values']['fedoraUser'];
	$fedoraPass  = $form_state['values']['fedoraPass'];
	
	$throttle = 1000;
	if (is_numeric($form_state['values']['throttle']) ) {
		$throttle = $form_state['values']['throttle'];
	}

	if (!$processFlag) {
		fedora_watchmen('Turning OFF Citebank Fedora cron PROCESSING.');
		drupal_set_message(t('Turning OFF Citebank Fedora cron PROCESSING. ' . $now));
	}
	
	variable_set('citebank_fedora_commons_throttle',     $throttle);
	variable_set('citebank_fedora_commons_throttleflag', $throttleFlag);
	variable_set('citebank_fedora_commons_hostserver',   $form_state['values']['hostServer']);
	variable_set('citebank_fedora_commons_namespace',    $form_state['values']['namespace']);
	variable_set('citebank_fedora_commons_loggingflag',  $loggingFlag);
	variable_set('citebank_fedora_commons_processflag',  $processFlag);

	variable_set('citebank_fedora_commons_fedorauser',  $fedoraUser);
	variable_set('citebank_fedora_commons_fedorapass',  $fedoraPass);
}

/**
 * citebank_fedora_commons_admin - 
 */
function citebank_fedora_commons_admin() 
{
  $form = array();

  $form['citebank_fedora_commons_maxdisp'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of links'),
    '#default_value' => variable_get('citebank_fedora_commons_maxdisp', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum number of links to display in the block."),
    '#required' => TRUE
  );

  return system_settings_form($form);
}

//drupal_set_message(t('Logging flag. ' . $configs['loggingFlag'] ));

/**
 * citebank_fedora_commons_configuration_form - 
 */
function citebank_fedora_commons_configuration_form($form_state) 
{
	$form = array();

	$configs['throttle']     = variable_get('citebank_fedora_commons_throttle', 1000);
	$configs['throttleFlag']  = (0 + variable_get('citebank_fedora_commons_throttleflag', 1) == 1 ? 1 : 0);  // 1 or 0 in database
	
	$configs['hostServer']   = variable_get('citebank_fedora_commons_hostserver', 'http://172.16.17.197:8080/fedora/');  // FIXME: get the production setting
	$configs['namespace']    = variable_get('citebank_fedora_commons_namespace', 'citebank');

	$configs['loggingFlag']  = (0 + variable_get('citebank_fedora_commons_loggingflag', 1) == 1 ? 1 : 0);  // 1 or 0 in database

	$configs['processFlag']  = (0 + variable_get('citebank_fedora_commons_processflag', 1) == 1 ? 1 : 0);  // 1 or 0 in database

	$configs['fedoraUser']    = variable_get('citebank_fedora_commons_fedorauser', 'fedoraAdmin');
	$configs['fedoraPass']    = variable_get('citebank_fedora_commons_fedorapass', 'fedoraAdmin');

	$form['namespace'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Name Space'),
	  '#default_value' => $configs['namespace'], // 'citebank',
    '#description' => t("The name used as part of the Fedora item identification. Set it to 'citebank' and leave it alone!")
	);

	$form['hostServer'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Host Server'),
	  '#default_value' => $configs['hostServer'], // 'http://172.16.17.197:8080/fedora/',
    '#description' => t("The Fedora host server address. REQUIRES an ending slash.  ex: http://123.123.123.123:8080/fedora/"),
	);

	$form['throttle'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Throttle Amount'),
	  '#default_value' => (is_numeric($configs['throttle']) ? $configs['throttle'] : '1000'), // '1000',
    '#description' => t("How many records to process each cron run. Suggested 100 or 1000.")
	);

	$form['throttleFlag'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Throttle Flag'),
	  '#default_value' => $configs['throttleFlag'], // '1',
    '#description' => t("Turns on/off throttling. Recommended that this be ON. Settings: 1 = ON, 0 = OFF")
	);

	$form['loggingFlag'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Logging Flag'),
	  '#default_value' => $configs['loggingFlag'], // '0',
    '#description' => t("Extra logging of processing steps (to diagnose problems). Recommended that this be OFF. Settings: 1 = ON, 0 = OFF")
	);

	//processFlag
	$form['processFlag'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Process Flag'),
	  '#default_value' => $configs['processFlag'], // '0',
    '#description' => t("Processing on and off switch, when ON will process records to send to the Fedora Repository. Recommended that this be ON. Settings: 1 = ON, 0 = OFF")
	);

	$form['fedoraUser'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Fedora user name'),
	  '#default_value' => $configs['fedoraUser'], // 'citebank',
    '#description' => t("Fedora user name.")
	);

	$form['fedoraPass'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Fedora pass word'),
	  '#default_value' => $configs['fedoraPass'], // 'citebank',
    '#description' => t("Fedora pass word.")
	);

	$form['submit'] = array(
	  '#type' => 'submit',
	  '#value' => 'SAVE CONFIGURATION',
	);
	$form['#submit'][] = 'citebank_fedora_commons_form_submit';
	
	return $form;
}


// ************************************************************
//  process import methods
// ************************************************************

/**
 *  processCiteBankFedoraCommons - 
 */
function processCiteBankFedoraCommons()
{
	$fedoraController = new FedoraController();
	
	if ($fedoraController->processFlag) {

		if ($fedoraController->loggingFlag) {
			fedora_watchmen('collecting citations, adding new ones, ready for fedora');
		}
		// add nodes to list and line them up for transfer
		$countItems = $fedoraController->processCitationsCollection();
		
		$throttleMsg = ($fedoraController->throttleFlag ? ' (throttled ' . $fedoraController->throttle . ')' : '');
	
		if ($fedoraController->loggingFlag) {
			fedora_watchmen('process citation collection ' . $countItems . ' citations to fedora' . $throttleMsg . '');
		}
	
		// take biblio citations that are ready and send them to our fedora repository
		$countItems = $fedoraController->processCitations();
	
		if ($fedoraController->loggingFlag) {
			fedora_watchmen('process citations ' . $countItems . ' citations to fedora' . $throttleMsg . '');
		}

	} else {
		fedora_watchmen('Citebank Fedora cron PROCESSING IS OFF');
	}
}


//watchdog($type, $message, $variables = array(), $severity = WATCHDOG_NOTICE, $link = NULL);
/**
 * watchmen - handy drupal watch logger, give it a msg and go
 */
function fedora_watchmen($msg, $watchFlag = true, $type = 'FedoraImp', $addDate = true)
{
	if ($watchFlag) {
		if ($addDate) {
			$msg .= ' ' . date('YmdHis');
		}
		
		watchdog($type, $msg);  // drupal system call
	}
}

// ************************************************************
// ************************************************************
