package at.co.ait.domain.oais;

import java.io.File;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Properties;
import java.util.Set;

/**
 * Payload encapsulates file and corresponding Metadata. A file object can
 * have multiple Metadata properties (e.g. type, size, creation date), but it can also 
 * have more sophisticated Metadata properties generated by metadata enrichment and
 * extraction tools (e.g. JHove, Aperture, Newzealand Metadata Extractor).
 * @author sprogerb
 *
 */
public class Payload {
	
	private File file;
	private Metadata metadata;
	
	public File getFile() {
		return file;
	}
	public void setFile(File file) {
		this.file = file;
	}
	public Metadata getMetadata() {
		return metadata;
	}
	public void setMetadata(Metadata metadata) {
		this.metadata = metadata;
	}

}
