bcp BHL.dbo.Creator in data\creator.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.ItemSource in data\itemsource.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Location in data\location.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.PageNameCount in data\pagenamecount.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.CreatorRoleType in data\creatorroletype.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Institution in data\institution.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.ItemStatus in data\itemstatus.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Language in data\language.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.MonthlyStats in data\monthlystats.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.PageType in data\pagetype.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.PaginationStatus in data\paginationstatus.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.TitleType in data\titletype.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Vault in data\vault.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Configuration in data\configuration.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.[User] in data\user.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.TitleIdentifier in data\titleidentifier.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.TitleAssociationType in data\titleassociationtype.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Title in data\title.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.TitleTag in data\titletag.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Title_Creator in data\title_creator.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Title_TitleIdentifier in data\title_titleidentifier.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Title_TitleType in data\title_titletype.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.TitleLanguage in data\titlelanguage.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.TitleAssociation in data\titleassociation.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.TitleAssociation_TitleIdentifier in data\titleassociation_titleidentifier.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Item in data\item.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.ItemLanguage in data\itemlanguage.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.TitleItem in data\titleitem.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Page in data\page.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.IndicatedPage in data\indicatedpage.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.Page_PageType in data\page_pagetype.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.PageName in data\pagename.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.PDFStatus in data\pdfstatus.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.PDF in data\pdf.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
bcp BHL.dbo.PDFPage in data\pdfpage.txt -c  -E -SBIOLINKDEV-W7\SQLEXPRESS -T
